export const SENSES = ['Eyes','Ears','Nose','Feel'];
export const SCENTS = {
 blood:{name:'Blood trace',color:'#d06a82',description:'A sharp metallic, organic trace. A wound can explain it; it does not identify a person.'},
 tar:{name:'Marine tar',color:'#809bb0',description:'Bitter, oily sealant used around the pier.'},
 pine:{name:'Pine polish',color:'#b2df9b',description:'Fresh resin and furniture polish.'},
 dust:{name:'Dry dust',color:'#aaa790',description:'Dry, stale, faint. Settled on quiet surfaces.'},
 wood:{name:'Wood & wax',color:'#c38d51',description:'Woody, dry, slightly sweet.'},
 coffee:{name:'Roasted coffee',color:'#cf824c',description:'Bitter, roasted, warm.'},
 anise:{name:'Anise & yeast',color:'#a9de6a',description:'Sweet, sharp, fermented. A distinctive bakery mixture.'},
 soap:{name:'Lemon detergent',color:'#f4ed7a',description:'Sharp citrus with a soapy finish.'},
 rain:{name:'Wet wool',color:'#81bcd9',description:'Damp cloth, faint street air.'},
 metal:{name:'Metallic residue',color:'#e78784',description:'Coppery and faint. Its source is not identified by smell alone.'},
 fuel:{name:'Fuel residue',color:'#d294ed',description:'Oily, volatile, sharp.'},
 earth:{name:'Wet soil',color:'#93bc69',description:'Earthy, damp, organic.'},
 bitter:{name:'Bitter plant extract',color:'#55d8b0',description:'Green, bitter, astringent.'},
 smoke:{name:'Combustion residue',color:'#e8a668',description:'Stale smoke and oily soot. A residue, not a reading of the air.'},
 orchid:{name:'Vanilla orchid',color:'#ef91c4',description:'Rich, sweet, floral.'},
 ozone:{name:'Scorched insulation',color:'#86aefa',description:'Hot plastic and acrid electrical residue.'},
 citrus:{name:'Orange tape cleaner',color:'#fbb968',description:'Sweet orange above a dry solvent note.'},
 lavender:{name:'Lavender',color:'#bcb1ff',description:'Dry, floral, herbal.'}
};
const o=(id,sense,title,text)=>({id,sense,title,text});
const p=(id,name,room,x,z,kind,observations,extra={})=>({id,name,room,x,z,kind,observations,...extra});
const r=(name,x,z,w,d,doors,color,type)=>({name,center:[x,z],size:[w,d],doors,color,type});
export const CASES=[{
 id:'blackthorn',number:'01',title:'One Guest Too Many',subtitle:'The killer has not left the house.',difficulty:'LIVE MANHUNT',stars:2,time:'EXPLORE · QUESTION · PURSUE',location:'BLACKTHORN MANOR',date:'23:47 · THE STORM',color:'#d8a77e',layout:'mansion',spawn:[0,13],bounds:[-17,17,-16,16],
 brief:'Elsie Blackthorn called you before the lights failed: “Someone here is pretending.” When you arrive, her father is dead in the library and three guests insist nobody entered it. Elsie is still inside with them. The front gate is chained shut by the storm. Find what happened, keep her safe, and stop the killer before the service exit opens.',
 facts:'NPCs move while you investigate. Switch to Ears to question them. You can inspect the rooms in any order. Confront a suspect with recorded evidence; be ready to follow them. Opening the notebook pauses the scene.',
 suspects:[{id:'voss',name:'Dr. Voss',role:'Family doctor',statement:'Says he stayed beside the conservatory heater all evening.'},{id:'mira',name:'Mira Bell',role:'Housekeeper',statement:'Says she cut her hand while preparing dessert.'},{id:'felix',name:'Felix Blackthorn',role:'Estranged son',statement:'Admits arguing with his father over the house.'}],
 rooms:[r('ENTRANCE HALL',0,10,10,12,{N:0},0x55433b,'foyer'),r('BALLROOM',0,-2,10,12,{N:0,S:0,W:0,E:0},0x6b473f,'ballroom'),r('LIBRARY',-11,-2,12,12,{E:0,N:0},0x354e45,'library'),r('DINING ROOM',11,-2,12,12,{W:0,N:0},0x594254,'dining'),r('WINTER GARDEN',-11,-12,12,8,{S:0,E:0},0x3c6056,'garden'),r('SERVANTS’ PASSAGE',0,-12,10,8,{S:0,W:0,E:0},0x3d484b,'passage'),r('SCULLERY',11,-12,12,8,{W:0,S:0},0x52615d,'kitchen')],
 objects:[
 p('elsie','Elsie Blackthorn',0,-2,0,'person',[o('m-elsie','Ears','Someone walking twice','“Please don’t leave me with them. Dad said the doctor used a cane. After the lights went out I heard fast steps—then someone started tapping a stick.”'),o('m-elsieeye','Eyes','Waiting by the door','Elsie grips the telephone cord. There is an unopened birthday card for her father in her coat pocket.')],{npc:true,coat:0xc2a356,role:'Caller',dialogue:'I know this house. The ballroom connects both wings. The narrow passage behind it reaches the kitchen and garden.',challenge:'Please look in the library. I’m staying by the front door.'}),
 p('voss','Dr. Voss',4,1,0,'person',[o('m-voss','Ears','The doctor’s account','“The heater. That is where I sat. My bad knee makes all this walking impossible. Blackthorn was alive when I last saw him.”'),o('m-vosseye','Eyes','The unfamiliar cuff','A green cuff is torn at the wrist. A fresh dressing peeks from underneath. His doctor’s badge reads “VOSS”; its portrait has a prominent white moustache. He has none.'),o('m-vossscent','Nose','Polish over a wound','Fresh pine polish overlays a metallic, organic trace at his sleeve.')],{npc:true,coat:0x426c5d,role:'Family doctor',scents:['pine','blood'],patrol:[[-10,-12],[0,-12],[0,-3],[-10,-3]],culprit:true,challengeEvidence:['m-vosseye','m-fabric','m-register'],challenge:'That register was never supposed to be here.',escape:[12,-13]}),
 p('mira','Mira Bell',6,2,0,'person',[o('m-mira','Ears','The ordinary cut','“Yes, that’s my blood on the chopping board. The knife slipped. I wrapped it before the blackout. Ask Elsie: she brought me the bandage.”'),o('m-miraeye','Eyes','A different dressing','Her left palm is bandaged. Both dark blue sleeves are intact.')],{npc:true,coat:0x303e65,role:'Housekeeper',scents:['blood','soap'],dialogue:'The service gate latch is in the scullery. If anyone runs, push it down. The outside catch will hold them.',challenge:'Blood alone? Look at the torn green fabric in the library. My uniform is blue.'}),
 p('felix','Felix Blackthorn',3,3,0,'person',[o('m-felix','Ears','An angry son','“I wanted him to sell this place, yes. I was on the phone to my solicitor when everything went dark. The dining-room machine recorded the call.”')],{npc:true,coat:0x825268,role:'Son',dialogue:'He was going to expose a fake charity tonight. The file is in the library. He wouldn’t tell me who was behind it.',challenge:'Play the dining-room message. You can hear my argument continuing through the blackout.'}),
 p('desk','Blackthorn’s writing desk',2,-3,-2,'desk',[o('m-register','Eyes','A caller already accounted for','The real Dr. Voss sent a telegram: “Still aboard the northern ferry. Arrive tomorrow.” Beside it: a charity account signed by Victor Senn, with a photograph matching the guest in the green coat.'),o('m-deskfeel','Feel','A fresh struggle','The desk edge has a fresh splinter. A thin sticky film sits beneath it.')]),
 p('fabric','Torn sleeve at the hearth',2,2,-3,'fragment',[o('m-fabric','Eyes','Green wool and a silver thread','A strip of green wool is caught on the fireplace grate. It has the same silver seam as the doctor’s torn cuff.'),o('m-fabricscent','Nose','A short trail','A blood trace mixed with pine polish continues toward the ballroom doorway.')],{scents:['blood','pine']}),
 p('body','Blackthorn’s covered body',2,1,2,'covered',[o('m-body','Eyes','The interrupted announcement','His hand is still around a programme: “Tonight: where the children’s home donations really went.” The broken desk lamp lies beside him.'),o('m-bodyfeel','Feel','A snapped cable','The lamp’s cable has been pulled from its fitting. The plug is cold; the weighted base is rough along one broken edge.')]),
 p('seat','Recently vacated armchair',4,-3,0,'armchair',[o('m-seat','Feel','Warm in the middle','The cushion’s centre is warmer than its edges. The nearby heater is cold. Someone occupied this chair recently; it does not prove they stayed here.'),o('m-seatnose','Nose','The polished sleeve','Pine polish is concentrated on one armrest, with a faint blood trace.')],{scents:['pine','blood'],physical:{temperature:33,texture:'compressed velvet',hardness:'yielding',roughness:.55,acoustic:'cloth'},warmSeat:true}),
 p('phone','Dining-room message machine',3,-3,-2,'radio',[o('m-call','Ears','The call crosses the blackout','Felix is arguing about the house. A loud click interrupts the recording, then he says, “The lights have gone. Are you still there?” The same voice continues without a break.')],{sound:'tape'}),
 p('knife','Scullery chopping board',6,-3,0,'utensils',[o('m-knife','Eyes','A small kitchen accident','A sliced lemon, a short paring knife, and a neatly folded blue sleeve cover sit beside a first-aid wrapper. The blood droplets are confined to the board.'),o('m-knifesmell','Nose','Blood and lemon','Blood is clear here, with lemon detergent. There is no pine-polish note.')],{scents:['blood','soap']}),
 p('gate','Service gate latch',6,2,-2,'lever',[o('m-gate','Feel','A heavy sliding catch','The warm inner handle moves freely. The outer catch drops into a steel staple. Pushing it down secures the service gate.')],{action:{id:'escape-secured',label:'Secure the service gate',sense:'Feel',message:'The service gate is secured. Anyone using this exit will have to stop.'}}),
 p('clock','Ballroom grandfather clock',1,3,1,'clock',[o('m-clock','Ears','The missing cane beat','The clock ticks evenly. Nearby footfalls sometimes arrive in quick pairs without the slower cane tap described by Elsie.')],{sound:'tick'})
 ],
 trails:[{scent:'blood',points:[[-9,-3],[-6,-3],[0,-3],[0,-10],[-9,-12]]},{scent:'pine',points:[[-8,-3],[-3,-3],[0,-8],[-8,-12]]}],
 leads:[{question:'Who was in the library?',where:'Enter through the ballroom. Inspect the writing desk and fabric at the hearth.',evidence:['m-register','m-fabric']},{question:'Does the doctor’s story fit?',where:'Question the guests with Ears. Compare the doctor’s cuff with the chair in the winter garden.',evidence:['m-vosseye','m-voss','m-seat']},{question:'Can you stop someone leaving?',where:'Trace the scullery gate latch with Feel. Show the suspect your recorded evidence when ready.',evidence:['m-gate']}],
 methods:['Posed as the doctor, struck Blackthorn with the desk lamp, and hid in the garden','The housekeeper stabbed Blackthorn with her kitchen knife','Felix killed his father during the recorded telephone argument'],motives:['Stop the exposure of a fraudulent children’s-home charity','Inherit the mansion immediately','Conceal theft from the household silver'],
 answer:{suspect:'voss',method:0,motive:0,evidence:['m-register','m-fabric','m-vosseye','m-voss','m-seat','m-body','m-elsie','m-vossscent']},requiredFlags:['detained'],
 resolution:'The guest calling himself Dr. Voss was Victor Senn, the organiser of the charity Blackthorn was about to expose. He struck Blackthorn with the weighted desk lamp and tore his cuff on the grate. Pine polish concealed part of the wound’s smell. The warm garden seat marked a recent hiding place, not a continuous alibi. Mira’s cut had an ordinary explanation; Felix’s recorded call crossed the blackout. Elsie can finally leave the house with someone she trusts.',
 hints:['Start with what Blackthorn was about to announce, not with the first blood you smell.','Compare the guest’s badge and cuff with the library papers and torn cloth.','Record the telegram, torn fabric, and doctor’s visible cuff. Question him with Ears and show the evidence. The scullery gate latch can stop his escape.']
},
{
 id:'last-car',number:'02',title:'Do Not Uncouple',subtitle:'Someone is knocking from the sealed carriage.',difficulty:'RESCUE & RECONSTRUCTION',stars:2,time:'LISTEN · RESTORE · RESCUE',location:'THE NORTHBOUND SLEEPER',date:'02:16 · SIGNAL FAILURE',color:'#8dc4d8',layout:'train',spawn:[-27,0],bounds:[-32,32,-3.5,3.5],
 brief:'The sleeper has stopped on an empty stretch of track. Ada, a passenger, says her brother Jo went to check a fault and never came back. The porter says he got off at the last station. Now someone is knocking from the sealed baggage car. Find Jo, open a way out, and discover why the train was stopped.',
 facts:'The train is stationary. There is no hidden countdown. The locked baggage bulkhead is real: listen through it, then find its release. Progress and rescued passengers remain saved. Conversations require Ears.',
 suspects:[{id:'porter',name:'Leon Wren',role:'Night porter',statement:'Insists Jo left the train at the previous stop.'},{id:'sable',name:'Sable Orr',role:'Courier',statement:'Has an expensive locked case and refuses to hand it over.'},{id:'ines',name:'Ines Holt',role:'Driver',statement:'Says she stopped because the signal relay vanished.'}],
 rooms:[r('OBSERVATION CAR',-26,0,12,7,{E:0},0x384c63,'lounge'),r('SLEEPING CAR',-13,0,14,7,{W:0,E:0},0x5b4452,'sleepers'),r('DINING CAR',1,0,14,7,{W:0,E:0},0x5f503b,'diner'),r('RELAY VESTIBULE',13,0,10,7,{W:0,E:0},0x3c5559,'electrical'),r('BAGGAGE CAR',25,0,14,7,{W:0},0x565047,'baggage')],
 objects:[
 p('ada','Ada Marin',0,-1,-1.8,'person',[o('t-ada','Ears','A signal from the other end','“Jo always knocks twice, waits, then once. We did it through our bedroom wall. Please just listen before they uncouple that car.”')],{npc:true,coat:0xc79564,role:'Jo’s sister',dialogue:'The porter took his tool roll past the dining car. Jo followed because he thought someone needed help.',challenge:'I’m not leaving without him.'}),
 p('porter','Leon Wren',2,0,-2,'person',[o('t-porter','Ears','An early departure','“Your missing man stepped off at North Junction. I was polishing the sleeper brass when the fault occurred. Baggage is out of bounds.”'),o('t-portereye','Eyes','The wrong tool roll','His roll has an empty rectangular pocket marked SIGNAL RELAY. Blue cable insulation is caught in its clasp.'),o('t-porterscent','Nose','Solvent on his gloves','Orange cleaner and fresh scorched insulation sit on the gloves.')],{npc:true,coat:0x466c7e,role:'Night porter',scents:['citrus','ozone'],patrol:[[1,-1.4],[8,0],[13,-1.4],[1,-1.4]],culprit:true,challengeEvidence:['t-testimony','t-roll','t-order'],challenge:'They were only paying me to stop the train. Jo should never have opened the bag.'}),
 p('sable','Sable Orr',1,-1,1.2,'person',[o('t-sable','Ears','The case nobody may touch','“It’s a restored violin. I can show the serial number and delivery letter. Suspicious luggage is apparently easier to find than a missing person.”'),o('t-sableeye','Eyes','A documented instrument','The opened case contains a violin. Its serial matches the conservatory’s delivery letter.')],{npc:true,coat:0x765d88,role:'Courier',dialogue:'There was an argument by the baggage door. One voice said, “Put the relay back.”',challenge:'Check the letter and instrument. Then please find the man.'}),
 p('ines','Ines Holt',3,1,-2,'person',[o('t-ines','Ears','A deliberate stop','“A relay was pulled; this wasn’t a random failure. The baggage door release lost power too. Restore its fuse here, or find the manual release inside the sleeper service locker.”')],{npc:true,coat:0x9e8244,role:'Driver',dialogue:'The release switch beside the baggage door needs power. A manual cable can open it without electricity.',challenge:'The event recorder shows when the relay failed. Compare it with the porter’s claimed routine.'}),
 p('jo','Jo Marin',4,3,1,'person',[o('t-testimony','Ears','The man who did not get off','“Leon pulled the relay. I saw him put it into his roll. Then he shoved me through this door. He said the transfer crew were waiting down the line.”'),o('t-joeye','Eyes','Very much on the train','Jo’s wrist has a rope mark and his work badge is bent. He can walk, but needs someone to open the door.')],{npc:true,coat:0xa06842,role:'Missing engineer',requires:'baggage-open',dialogue:'Ada’s here? Get me back to her. I thought nobody could hear me.',action:{id:'rescued',label:'Ask Jo to follow you to Ada',message:'Jo is safe with Ada in the observation car.'}}),
 p('bulkhead','Sealed baggage bulkhead',3,4.65,0,'bulkhead',[o('t-knock','Ears','Two, a pause, then one','Two knocks. A pause. One knock. A muffled voice follows: “The handle does nothing from this side.”'),o('t-doorfeel','Feel','A locked door under pressure','The door is shut against its latch. A pulse from each knock carries through the lower panel.')],{sound:'rescue',action:{id:'baggage-open',label:'Pull the powered door release',sense:'Feel',needs:['power'],message:'The baggage bulkhead slides aside. There is someone inside.'}}),
 p('fuse','Door circuit fuse holder',3,-2,2.1,'fusebox',[o('t-fuse','Eyes','One missing connection','The release circuit’s fuse is loose in its holder. A diagram labels it BAGGAGE DOOR, separate from the missing signal relay.'),o('t-fusefeel','Feel','Loose, not burnt','The ceramic fuse is cool and intact. Its retaining clip has been deliberately lifted.')],{action:{id:'power',label:'Seat the loose fuse',sense:'Feel',message:'The baggage release clicks on. Return to the bulkhead and pull the release.'}}),
 p('locker','Sleeper service locker',1,4,2,'cabinet',[o('t-locker','Feel','A cable behind the lining','A stout cable runs behind a loose panel. A stamped tag reads BAGGAGE MANUAL RELEASE.'),o('t-lockerear','Ears','A long mechanical connection','Tugging the cable makes something clack at the distant baggage door.')],{action:{id:'baggage-open',label:'Pull the manual release cable',sense:'Feel',message:'The manual cable pulls the baggage door latch clear.'}}),
 p('roll','Porter’s spare tool roll',2,3,2,'toolroll',[o('t-roll','Eyes','A relay wrapped for collection','A signal relay is wrapped in a service cloth. Its serial matches the missing unit on the driver’s fault card.'),o('t-rollnose','Nose','Fresh cleaner on the contacts','Orange cleaner overlays the same scorched-insulation note as the porter’s gloves.')],{scents:['citrus','ozone']}),
 p('order','Crushed transfer order',2,-3,2,'ticket',[o('t-order','Eyes','A paid unscheduled stop','“L. Wren: hold the sleeper between signals 18 and 19. Transfer the bearer bonds. Balance on delivery.” The station stop at North Junction was cancelled.'),o('t-orderfeel','Feel','Recently crushed paper','The paper is damp where it was tightly crumpled. Its perforated edge matches a stub on the porter’s service clipboard.')]),
 p('seat','Warm sleeper bunk',1,-4,1.9,'bunk',[o('t-seat','Feel','A body-shaped hollow','The centre retains warmth while the window-side blanket is cold. A body recently left this bunk.'),o('t-seatnose','Nose','An ordinary traveller','Coffee and wet wool. There is no orange-cleaner note.')],{warmSeat:true,scents:['coffee','rain'],physical:{temperature:32,texture:'creased blanket',hardness:'yielding',roughness:.6,acoustic:'cloth'}}),
 p('recorder','Train event recorder',0,3,2,'console',[o('t-log','Eyes','The stop that never happened','North Junction: PASS THROUGH. 02:09 relay circuit interrupted. 02:10 emergency stop. No doors opened before the stop.'),o('t-logear','Ears','A live recorder','The relay monitor pulses slowly. The passenger announcement repeats automatically; it is not the porter speaking now.')],{sound:'hum'})
 ],
 trails:[{scent:'citrus',points:[[-12,0],[-3,0],[5,0],[13,0],[17,0]]},{scent:'ozone',points:[[12,2],[12,0],[5,0]]}],
 leads:[{question:'Is someone still in the baggage car?',where:'Follow the central aisle to the far end. Listen to the bulkhead with Ears.',evidence:['t-ada','t-knock']},{question:'Can you open the door?',where:'Feel the relay vestibule fuse holder, or find the sleeper’s manual cable.',evidence:['t-fusefeel']},{question:'Why was this train stopped?',where:'Compare the event recorder, tool roll, and crushed transfer order. Speak with Jo once he is free.',evidence:['t-log','t-roll','t-order','t-testimony']}],
 methods:['Removed the signal relay and locked Jo in baggage after he witnessed the theft','The courier sabotaged the train to hide a stolen violin','The driver caused an accidental failure and Jo left at North Junction'],motives:['Stop the train for a paid robbery of bearer bonds','Collect a reward for rescuing Jo','Delay delivery of the conservatory’s violin'],
 answer:{suspect:'porter',method:0,motive:0,evidence:['t-testimony','t-roll','t-order','t-log','t-portereye','t-porterscent','t-knock','t-ada']},requiredFlags:['rescued','detained'],
 resolution:'Leon pulled the signal relay to create an unscheduled stop for a robbery crew. Jo caught him and was locked into the unpowered baggage car. The cancelled station stop made Leon’s story impossible. Jo’s knocking kept the rescue possible even when sight could not reach him. Restoring the release—or pulling its manual cable—brought him back to Ada. With the relay, payment order, and Jo’s testimony preserved, Leon cannot pass this off as a fault.',
 hints:['Walk toward the knocking. The missing man’s sister can tell you what to listen for.','The driver offers two ways into baggage: an electrical release and a manual cable.','Free Jo, lead him back to Ada, then record his account, the relay in the tool roll, and the transfer order. Question Leon and present those observations.']
},
{
 id:'pier-pressure',number:'03',title:'Pier Pressure',subtitle:'The money is moving. So is the gunman.',difficulty:'ACTIVE PURSUIT',stars:3,time:'TRACK · CUT OFF · TAKE COVER',location:'ROOKERY FERRY DOCK',date:'04:32 · BEFORE FIRST SAILING',color:'#7cafa8',layout:'docks',spawn:[-12,12],bounds:[-18,18,-18,16],
 brief:'Rookery’s ferry crew raised enough to keep their last boat running through winter. Tonight the fund was stolen, a dockworker was wounded, and the security guard wants to arrest the mechanic. The ferry dispatcher refuses to sail without the money. Search the freight yard, find the stolen case, and stop whoever is still moving it toward the launch.',
 facts:'The dock has cover, open sightlines, and several routes around the freight stacks. A confrontation can become dangerous. Stay behind solid cover when the gunman aims. If pinned down, you return to the entrance with your evidence intact. Pausing freezes the action.',
 suspects:[{id:'rook',name:'Cal Rook',role:'Security guard',statement:'Says he fired at the thief and saw the mechanic run.'},{id:'bea',name:'Bea Moss',role:'Ferry mechanic',statement:'Says she ran toward the shot to help the wounded worker.'},{id:'otto',name:'Otto Vale',role:'Cargo broker',statement:'Was selling a boat part privately after hours.'}],
 rooms:[r('FERRY FORECOURT',-9,9,18,14,{},0x485d61,'yard'),r('FREIGHT MAZE',2,-3,22,24,{},0x374d52,'freight'),r('DISPATCH SHED',-13,-10,10,12,{E:0,S:0},0x426761,'shed'),r('REPAIR BAY',12,9,12,14,{W:0,N:0},0x4d5665,'garage'),r('LAUNCH PIER',10,-16,16,4,{},0x655c4a,'pier')],
 objects:[
 p('nell','Nell Finch',0,-3,0,'person',[o('d-nell','Ears','One winter of crossings','“My mum takes the early ferry to work. Half the town does. We counted that money together. Find the case before it leaves the pier.”')],{npc:true,coat:0xc38e4e,role:'Dispatcher',dialogue:'The launch fuel valve is at the end of the pier. Close it before confronting anyone who might run for the boat.',challenge:'The fundraiser sheet is on the counter. Every name is someone who needs this ferry.'}),
 p('rook','Cal Rook',1,3,2,'person',[o('d-rook','Ears','The guard’s version','“Moss ran from the gate after I fired. I’m the only armed guard here. Let me take her in, and you can stop wasting time.”'),o('d-rookeye','Eyes','A torn boot and fresh dressing','His right boot has a split heel. A dressing crosses his left forearm. The holster strap is unsnapped.'),o('d-rookscent','Nose','Tar over blood','Fresh marine tar overlays blood near the cuff. Rain has not washed it away.')],{npc:true,coat:0x414b68,role:'Security guard',scents:['blood','tar'],patrol:[[4,-2],[4,-10],[10,-10],[10,-16],[4,-10]],culprit:true,armed:true,challengeEvidence:['d-case','d-camera','d-boot'],challenge:'You should have let me finish the report.',escape:[15,-16]}),
 p('bea','Bea Moss',3,-1,2,'person',[o('d-bea','Ears','Running toward the shot','“I heard the shot and went to help Sam. Rook told me to go back to my bay. I didn’t see a thief—only the guard and Sam.”'),o('d-beaeye','Eyes','Work boots without the split','Both boot heels are intact. Her hands and sleeves carry ordinary engine oil, with no fresh wound.')],{npc:true,coat:0x526c83,role:'Mechanic',dialogue:'Sam is under the dispatch awning. He can tell you which direction the shot came from.',challenge:'Check the heel marks. My soles don’t leave that split.'}),
 p('otto','Otto Vale',0,4,-3,'person',[o('d-otto','Ears','A different secret','“Fine. I sold a starter motor without logging it. That’s my fuel on the trolley. It doesn’t make me your armed robber.”')],{npc:true,coat:0x7e6051,role:'Cargo broker',dialogue:'The guard’s locker is in dispatch. He went there before the launch engine started.',challenge:'The buyer’s receipt is on the trolley. It describes a motor, not your cash case.'}),
 p('sam','Sam Reed',2,1,3,'person',[o('d-sam','Ears','The shot from behind','“I saw him move the fundraiser case. I grabbed his sleeve. He fired when I turned toward Nell. The shot came from the freight side, not the road.”')],{npc:true,coat:0x967755,role:'Wounded dockworker',dialogue:'I’m bandaged. Help is coming. Please keep Nell away from the guard.',injured:true}),
 p('case','Fundraiser cash case',1,1,-5,'cashcase',[o('d-case','Eyes','The town’s missing case','The case has the ferry logo and fundraiser seal. Its leather handle is wrapped in a security-uniform sleeve.'),o('d-casescent','Nose','The same mixture','Blood and fresh marine tar cling to the sleeve and handle.')],{scents:['blood','tar']}),
 p('camera','Dispatch security recorder',2,-2,-2,'console',[o('d-camera','Eyes','The report contradicts its own camera','A still shows Rook carrying the ferry case into the freight yard before the shot. His written report says he never left the gate.'),o('d-cameraear','Ears','The shot’s sequence','The recorded shot follows Sam calling, “Cal, put it down.” The launch engine starts afterwards.')],{sound:'tape'}),
 p('boot','Split heel impressions',1,-8,7,'tracks',[o('d-boot','Eyes','One broken heel','The wet impressions show a split right heel. They run from dispatch toward the freight stacks and continue to the launch.'),o('d-bootfeel','Feel','A gap in the tread','The right print has a deep missing wedge at its outside edge. The left print is complete.'),o('d-bootscent','Nose','Tar carried along the boards','Marine tar follows the heel impressions. A blood trace joins it farther into the yard.')],{scents:['tar','blood']}),
 p('blood','Drops beside the freight stack',1,0,1,'fragment',[o('d-blood','Eyes','Two directions after the shot','A few dark drops continue toward the launch. The larger patch lies beside Sam’s dropped cap, toward dispatch.'),o('d-bloodnose','Nose','Fresh and carried','Blood is present on both routes. Tar is mixed only with the trail toward the launch.')],{scents:['blood','tar']}),
 p('valve','Launch fuel shutoff',4,1,0,'valve',[o('d-valve','Feel','A quarter-turn stop','The valve vibrates with the launch engine. Its stop plate reads CLOSE. Turn it to stop the fuel supply.')],{physical:{temperature:27,texture:'ribbed wheel',hardness:'rigid',roughness:.3,acoustic:'metal',vibration:true},action:{id:'escape-secured',label:'Close the launch fuel valve',sense:'Feel',message:'The launch engine winds down. The boat cannot leave.'}}),
 p('bench','Guard’s shelter bench',2,1,-3,'bench',[o('d-bench','Feel','Someone just stood up','The sheltered end of the bench is warm and compressed. The exposed end is cold and wet.'),o('d-benchnose','Nose','Fresh sealant on the seat','Tar and a small blood trace sit on the sheltered end.')],{warmSeat:true,scents:['tar','blood'],physical:{temperature:32,texture:'damp canvas cushion',hardness:'yielding',roughness:.6,acoustic:'cloth'}}),
 p('fund','Ferry fundraiser board',0,-3,-4,'ticket',[o('d-fund','Eyes','A community in small amounts','£8 from the baker. £3 from the night cleaner. £12 from Sam. The total matches the amount marked on the stolen case. This was the winter fuel fund.')]),
 p('motor','Unlogged starter motor',3,-2,-2,'trolley',[o('d-motor','Eyes','A petty deal','A handwritten receipt from Otto lists one used starter motor. A buyer’s signature and motor serial agree.'),o('d-motornose','Nose','An ordinary fuel source','Old engine fuel and oil. No blood or freshly applied marine tar.')],{scents:['fuel']})
 ],
 trails:[{scent:'tar',points:[[-11,-10],[-7,-10],[-3,-7],[4,-7],[4,-10],[10,-10],[10,-16]]},{scent:'blood',points:[[-11,-7],[-7,-7],[0,-2],[4,-2],[4,-10],[10,-16]]}],
 leads:[{question:'Who saw the theft, not just the aftermath?',where:'Speak with Nell, Sam, and the workers using Ears. Check the dispatch recorder.',evidence:['d-nell','d-sam','d-camera']},{question:'Where is the stolen case going?',where:'Compare the heel impressions, blood, and tar through the freight maze. Check the guard’s boots.',evidence:['d-boot','d-case','d-rookeye']},{question:'Can you prevent a getaway?',where:'Close the launch valve before showing your evidence. Use the freight stacks as cover if threatened.',evidence:['d-valve']}],
 methods:['Stole the case, shot the witness, and framed the mechanic while moving it to the launch','The mechanic stole the fund and fled through the front gate','The cargo broker hid the fund inside the sold starter motor'],motives:['Take the winter ferry fund and escape by launch','Hide an unlogged spare-parts sale','Get the mechanic dismissed for poor work'],
 answer:{suspect:'rook',method:0,motive:0,evidence:['d-case','d-camera','d-cameraear','d-boot','d-rookeye','d-rookscent','d-sam','d-casescent']},requiredFlags:['detained'],
 resolution:'Rook used his security access to take the winter fund. Sam caught him and grabbed his sleeve; Rook shot him and tried to redirect the investigation toward Bea. The recorder, uniform wrapping, split heel, and blood mixed with fresh tar establish a route and a person. Otto’s unlogged motor was a separate offence. With the launch stopped and Rook detained, Nell can return the money to the ferry crew. Sam’s contribution stays on the board.',
 hints:['Speak to the people who were here. Rook’s accusation is one account, not a finding.','The dispatch recorder and split heel trail contradict the guard’s claimed position. Find the cash case among the freight stacks.','Record the case, recorder, and heel impressions. Close the launch valve with Feel, then question Rook and show him the evidence. Take cover when he aims; approach between shots.']
}
];
