import * as THREE from './vendor/three.module.js';
import {SCENTS} from './cases.js';
import {contactAt,temperatureColor} from './materials.js';
const V=THREE.Vector3;
const visible=m=>{for(let p=m;p;p=p.parent)if(!p.visible)return false;return true;};
export const SENSORY_TIMING={echo:5,touch:180,scent:300,inhale:5,cooldown:15};
export class Breath {
 constructor(){this.held=false;this.elapsed=0;this.cooldown=0;this.exhale=0;this.needsRelease=false;this.range=3;}
 begin(){if(this.cooldown>0||this.exhale>0||this.needsRelease)return false;this.held=true;this.elapsed=0;this.range=3;return true;}
 release(){if(this.held)this.exhale=.6;this.held=false;this.elapsed=0;this.range=3;this.needsRelease=false;}
 tick(dt){this.cooldown=Math.max(0,this.cooldown-dt);this.exhale=Math.max(0,this.exhale-dt);if(this.held){this.elapsed=Math.min(5,this.elapsed+dt);this.range=3+this.elapsed*3.2;if(this.elapsed>=5-1e-6){this.held=false;this.cooldown=15;this.exhale=1;this.needsRelease=true;return true;}}return false;}
}
// Static bounds accelerate thousands of sniff rays without revealing objects through walls.
export class SurfaceIndex {
 constructor(meshes){this.raycaster=new THREE.Raycaster();this.stack=[];const entries=meshes.map(mesh=>{mesh.updateWorldMatrix(true,false);if(!mesh.geometry.boundingBox)mesh.geometry.computeBoundingBox();return{mesh,box:mesh.geometry.boundingBox.clone().applyMatrix4(mesh.matrixWorld)};});this.root=this.build(entries);}
 build(entries){if(!entries.length)return null;const box=new THREE.Box3();entries.forEach(e=>box.union(e.box));if(entries.length<=6)return{box,entries};const s=box.getSize(new V()),axis=s.x>s.y&&s.x>s.z?'x':s.y>s.z?'y':'z';entries.sort((a,b)=>(a.box.min[axis]+a.box.max[axis])-(b.box.min[axis]+b.box.max[axis]));const mid=entries.length>>1;return{box,left:this.build(entries.slice(0,mid)),right:this.build(entries.slice(mid))};}
 cast(origin,dir,far=30){const r=this.raycaster;r.set(origin,dir);r.near=.005;r.far=far;let best=null;const stack=[this.root],point=new V();while(stack.length){const node=stack.pop();if(!node||!r.ray.intersectBox(node.box,point))continue;if(!node.box.containsPoint(origin)&&point.distanceTo(origin)>r.far+.01)continue;if(node.entries){for(const e of node.entries){if(!visible(e.mesh)||!r.ray.intersectsBox(e.box))continue;const hits=[];e.mesh.raycast(r,hits);for(const hit of hits)if(hit.distance>=r.near&&hit.distance<r.far){best=hit;r.far=hit.distance;}}}else stack.push(node.left,node.right);}return best;}
}
function clip(poly,axis,bound,sign){const out=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],da=sign*(a[axis]-bound),db=sign*(b[axis]-bound);if(da<=0)out.push(a);if((da<=0)!==(db<=0)){const t=da/(da-db);out.push({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t});}}return out;}
// Clip each mark to the actual struck face, so it shows a wall, floor or object rather than floating in space.
export function surfacePatch(hit,radius){if(!hit?.face)return[];const mesh=hit.object,normal=hit.face.normal.clone().transformDirection(mesh.matrixWorld).normalize(),axis=Math.abs(normal.y)<.9?new V(0,1,0):new V(1,0,0),u=new V().crossVectors(axis,normal).normalize(),v=new V().crossVectors(normal,u);const geo=mesh.geometry,position=geo.attributes.position,index=geo.index,origin=hit.point,vertices=[];const count=index?index.count:position.count;
 for(let i=0;i<count;i+=3){const tri=[0,1,2].map(j=>new V().fromBufferAttribute(position,index?index.getX(i+j):i+j).applyMatrix4(mesh.matrixWorld));const n=new V().subVectors(tri[1],tri[0]).cross(new V().subVectors(tri[2],tri[0])).normalize();if(n.dot(normal)<.94||tri.some(p=>Math.abs(p.clone().sub(origin).dot(normal))>.045))continue;let poly=tri.map(p=>{const d=p.clone().sub(origin);return{x:d.dot(u),y:d.dot(v)}});poly=clip(clip(clip(clip(poly,'x',radius,1),'x',-radius,-1),'y',radius,1),'y',-radius,-1);for(let j=1;j<poly.length-1;j++)for(const a of [poly[0],poly[j],poly[j+1]]){const p=origin.clone().addScaledVector(u,a.x).addScaledVector(v,a.y).addScaledVector(normal,.009);vertices.push({p,x:a.x/radius,y:a.y/radius});}}
 return vertices;
}
export class SurfaceMarks {
 constructor(scene,color,lifetime,capacity){this.lifetime=lifetime;this.capacity=capacity;this.slotSize=48;this.cursor=0;this.count=0;this.records=new Map();const n=capacity*this.slotSize,g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(new Float32Array(n*3),3).setUsage(THREE.DynamicDrawUsage));g.setAttribute('aUV',new THREE.BufferAttribute(new Float32Array(n*2),2).setUsage(THREE.DynamicDrawUsage));g.setAttribute('aBorn',new THREE.BufferAttribute(new Float32Array(n).fill(-10000),1).setUsage(THREE.DynamicDrawUsage));g.setAttribute('aTint',new THREE.BufferAttribute(new Float32Array(n*3),3).setUsage(THREE.DynamicDrawUsage));g.setAttribute('aFeel',new THREE.BufferAttribute(new Float32Array(n*3),3).setUsage(THREE.DynamicDrawUsage));g.setDrawRange(0,0);this.geometry=g;this.material=new THREE.ShaderMaterial({transparent:true,depthWrite:false,depthTest:true,toneMapped:false,side:THREE.DoubleSide,uniforms:{uTime:{value:0},uLife:{value:lifetime},uColor:{value:new THREE.Color(color)}},vertexShader:`attribute vec2 aUV;attribute float aBorn;attribute vec3 aTint;attribute vec3 aFeel;varying vec3 vTint;varying vec3 vFeel;varying vec2 vUV;varying float vAge;uniform float uTime;void main(){vTint=aTint;vFeel=aFeel;vUV=aUV;vAge=uTime-aBorn;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`varying vec3 vTint;varying vec3 vFeel;varying vec2 vUV;varying float vAge;uniform float uLife;uniform vec3 uColor;void main(){float radius=length(vUV);if(radius>1.0||vAge<0.0||vAge>=uLife)discard;float opacity=(1.0-smoothstep(.15,1.0,radius))*pow(max(0.0,1.0-vAge/uLife),.75);float grain=mix(1.0,.55+.45*abs(sin(vUV.x*37.0)*sin(vUV.y*43.0)),vFeel.x);float pulse=1.0-vFeel.z*.2*(.5+.5*sin(vAge*32.0));float wet=1.0-vFeel.y*.15*(.5+.5*sin(length(vUV)*28.0-vAge*2.0));gl_FragColor=vec4(vTint,opacity*.9*grain*pulse*wet);}`});this.mesh=new THREE.Mesh(g,this.material);this.mesh.frustumCulled=false;this.mesh.renderOrder=2;scene.add(this.mesh);}
 add(hit,now,radius=.55){const key=hit.object.uuid+':'+[hit.point.x,hit.point.y,hit.point.z].map(x=>Math.round(x/.15)).join(',');const old=this.records.get(key);let slot=old?.slot;if(slot===undefined){const verts=surfacePatch(hit,radius);if(!verts.length)return false;slot=this.cursor++%this.capacity;for(const [k,r]of this.records)if(r.slot===slot){this.records.delete(k);break;}const base=slot*this.slotSize;for(let i=0;i<this.slotSize;i++){const a=verts[i];this.geometry.attributes.position.setXYZ(base+i,a?a.p.x:0,a?a.p.y:0,a?a.p.z:0);this.geometry.attributes.aUV.setXY(base+i,a?a.x:2,a?a.y:2);}this.records.set(key,{slot,point:hit.point.clone(),mesh:hit.object,at:now});this.count=Math.min(this.capacity,this.count+1);}else old.at=now;
 const base=slot*this.slotSize,physical=contactAt(hit),tactile=this.lifetime===180,tint=tactile?temperatureColor(physical.temperature):this.material.uniforms.uColor.value;for(let i=0;i<this.slotSize;i++){this.geometry.attributes.aBorn.setX(base+i,now);this.geometry.attributes.aTint.setXYZ(base+i,tint.r,tint.g,tint.b);this.geometry.attributes.aFeel.setXYZ(base+i,tactile?physical.roughness:0,tactile&&physical.wetness?1:0,tactile&&physical.vibration?1:0);}this.geometry.setDrawRange(0,this.count*this.slotSize);for(const a of Object.values(this.geometry.attributes))a.needsUpdate=true;return true;}
 hasNear(hit,now){for(const r of this.records.values())if(r.mesh===hit.object&&now-r.at<this.lifetime&&r.point.distanceTo(hit.point)<.85)return true;return false;}
 update(now,on){this.material.uniforms.uTime.value=now;this.mesh.visible=on;}
 dispose(){this.mesh.removeFromParent();this.geometry.dispose();this.material.dispose();}
}
function radical(n,base){let value=0,f=1/base;while(n>0){value+=(n%base)*f;n=Math.floor(n/base);f/=base;}return value;}
// Hash independently of the low-discrepancy camera coordinates. Modulo selection biases the scan.
export function flowSelection(n){let x=Math.imul(n^0x9e3779b9,0x21f0aaad);x=Math.imul(x^(x>>>15),0x735a2d97);return ((x^(x>>>15))>>>0)/4294967296;}
export const scentSpeed=(distance,familiar=false)=>(.5+14/(distance+1.5))*(familiar?1.7:1);
// A straight camera ray has constant projected x/y: dots appear stationary.
// A converging current also pulls across the view plane, creating visible parallax.
// Normalize the direction so travel speed still depends only on proximity/familiarity.
export function advanceScent(stream,camera,dt){
 const local=stream.p.clone().sub(camera.position).applyQuaternion(camera.quaternion.clone().invert());
 const distance=local.length();if(distance<.001)return;
 local.set(-local.x*2.4,-local.y*2.4,-local.z).normalize().applyQuaternion(camera.quaternion);
 stream.p.addScaledVector(local,Math.min(distance*.35,scentSpeed(distance,stream.familiar)*dt));
}
export class ScentScanner {
 constructor(world){this.world=world;this.index=new SurfaceIndex(world.surfaces);this.breath=new Breath();this.keys=Object.keys(SCENTS);this.familiar=new Set();this.pointsByCell=new Map();this.cursor=0;this.count=0;this.sample=1;this.scanBudget=0;this.streams=[];this.filter=-1;this.capacity=100000;this.lastStatus='';const n=this.capacity,g=new THREE.BufferGeometry();for(const [name,size,fill]of[['position',3,0],['color',3,0],['aSeen',1,-10000],['aScent',1,0]])g.setAttribute(name,new THREE.BufferAttribute(new Float32Array(n*size).fill(fill),size).setUsage(THREE.DynamicDrawUsage));g.setDrawRange(0,0);this.geometry=g;this.material=new THREE.ShaderMaterial({transparent:true,depthWrite:false,depthTest:true,vertexColors:true,toneMapped:false,uniforms:{uTime:{value:0},uFilter:{value:-1},uPixel:{value:Math.min(globalThis.devicePixelRatio||1,1.6)}},vertexShader:`attribute float aSeen;attribute float aScent;varying vec3 vColor;varying float vAlpha;uniform float uTime;uniform float uFilter;uniform float uPixel;void main(){float age=uTime-aSeen;vColor=color;vAlpha=age>=0.0&&age<300.0?pow(1.0-age/300.0,.55):0.0;if(uFilter>=0.0&&abs(aScent-uFilter)>.1)vAlpha=0.0;vec4 mv=modelViewMatrix*vec4(position,1.0);gl_Position=projectionMatrix*mv;gl_PointSize=clamp(25.0*uPixel/max(.1,-mv.z),1.6,5.5);}`,fragmentShader:`varying vec3 vColor;varying float vAlpha;void main(){float radius=length(gl_PointCoord-vec2(.5));if(radius>.5||vAlpha<.001)discard;gl_FragColor=vec4(vColor,vAlpha*(1.0-smoothstep(.22,.5,radius)));}`});this.points=new THREE.Points(g,this.material);this.points.frustumCulled=false;this.points.renderOrder=3;world.scene.add(this.points);
 this.flowGeometry=new THREE.BufferGeometry();this.flowGeometry.setAttribute('position',new THREE.BufferAttribute(new Float32Array(3600),3).setUsage(THREE.DynamicDrawUsage));this.flowGeometry.setAttribute('color',new THREE.BufferAttribute(new Float32Array(3600),3).setUsage(THREE.DynamicDrawUsage));this.flowGeometry.setDrawRange(0,0);this.flowMaterial=new THREE.ShaderMaterial({vertexColors:true,transparent:true,depthTest:true,depthWrite:false,toneMapped:false,uniforms:{uPixel:this.material.uniforms.uPixel},vertexShader:`varying vec3 vColor;varying float vAlpha;uniform float uPixel;void main(){vColor=color;vec4 mv=modelViewMatrix*vec4(position,1.0);vAlpha=smoothstep(.2,.65,length(mv.xyz));gl_Position=projectionMatrix*mv;gl_PointSize=clamp(25.0*uPixel/max(.1,-mv.z),1.6,5.5);}`,fragmentShader:this.material.fragmentShader});this.flowPoints=new THREE.Points(this.flowGeometry,this.flowMaterial);this.flowPoints.frustumCulled=false;this.flowPoints.renderOrder=4;world.scene.add(this.flowPoints);
 }
 rebuild(){this.index=new SurfaceIndex(this.world.surfaces);}
 begin(){return this.breath.begin();}
 release(){this.breath.release();}
 setFilter(id){this.filter=id?this.keys.indexOf(id):-1;this.material.uniforms.uFilter.value=this.filter;}
 scentAt(hit){let choices=hit.object.userData.scents||['dust'];if(hit.point.y<.14){let closest=.35;for(const p of this.world.particleData){if(!p.trail&&!p.transfer)continue;const d=Math.hypot(p.x-hit.point.x,p.z-hit.point.z);if(d<closest){closest=d;choices=[p.scent];}}}const hash=Math.abs(Math.sin(hit.point.x*17+hit.point.y*7+hit.point.z*11));return choices[Math.floor(hash*choices.length)]||'dust';}
 remember(hit,now){const scent=this.scentAt(hit),normal=hit.face.normal.clone().transformDirection(hit.object.matrixWorld),p=hit.point.clone().addScaledVector(normal,.018);const key=hit.object.uuid+':'+[p.x,p.y,p.z].map(n=>Math.round(n/.045)).join(',');let record=this.pointsByCell.get(key);const familiar=this.familiar.has(scent);if(!record){const slot=this.cursor++%this.capacity;record={slot,at:now,point:hit.point.clone(),mesh:hit.object,scent};if(this.count===this.capacity){for(const [k,v]of this.pointsByCell)if(v.slot===slot){this.pointsByCell.delete(k);break;}}this.pointsByCell.set(key,record);this.count=Math.min(this.capacity,this.count+1);this.geometry.attributes.position.setXYZ(slot,p.x,p.y,p.z);const c=new THREE.Color(SCENTS[scent].color);this.geometry.attributes.color.setXYZ(slot,c.r,c.g,c.b);this.geometry.attributes.aScent.setX(slot,this.keys.indexOf(scent));}if(flowSelection(this.sample)<.25&&this.streams.length<1200)this.streams.push({p:p.clone(),origin:p.clone(),scent,familiar,age:0});record.at=now;this.geometry.attributes.aSeen.setX(record.slot,now);if(!familiar){this.familiar.add(scent);this.world.events.scents?.([scent]);}}
 scan(count,range,focus=null){const camera=this.world.camera;camera.updateMatrixWorld(true);const aspect=camera.aspect,tan=Math.tan(camera.fov*Math.PI/360);for(let i=0;i<count;i++){const k=this.sample++,x=focus?THREE.MathUtils.clamp(focus.x+(radical(k,2)*2-1)*.13,-1,1):(radical(k,2)*2-1)*.92,y=focus?THREE.MathUtils.clamp(focus.y+(radical(k,3)*2-1)*.13,-1,1):(radical(k,3)*2-1)*.92;const dir=new V(x*tan*aspect,y*tan,-1).normalize().applyQuaternion(camera.quaternion);const hit=this.index.cast(camera.position,dir,range);if(hit)this.remember(hit,this.world.time);}this.geometry.setDrawRange(0,this.count);for(const a of Object.values(this.geometry.attributes))a.needsUpdate=true;}
 hasNear(hit,now){for(const r of this.pointsByCell.values())if(r.mesh===hit.object&&now-r.at<300&&r.point.distanceTo(hit.point)<.4&&(this.filter<0||this.keys.indexOf(r.scent)===this.filter))return true;return false;}
 update(dt,enabled,canSniff){const menu=this.world.mode==='menu',menuSniff=menu&&enabled&&canSniff&&this.world.menuPerception?.engaged;const b=this.breath;if(!enabled||!canSniff){if(b.held)b.release();}const was=b.held,range=b.range,forced=b.tick(dt);if(menuSniff){this.scan(Math.min(320,Math.ceil(dt*5600)),110,this.world.menuPerception.cursor);}else if(!menu&&was&&enabled&&canSniff){this.scanBudget+=dt*4700;const count=Math.min(400,Math.floor(this.scanBudget));this.scanBudget-=count;this.scan(count,Math.max(range,b.range));}if(forced)this.world.events.message?.('Exhale. Catch your breath for 15 seconds.');const target=this.world.camera.position;let n=0;for(let i=this.streams.length-1;i>=0;i--){const s=this.streams[i],distance=s.p.distanceTo(target);s.age+=dt;if(distance<.25||s.age>(menu?24:9)||(!b.held&&!menuSniff&&s.age>1.2)){this.streams.splice(i,1);continue;}if(b.held||menuSniff)advanceScent(s,this.world.camera,dt);if(this.filter>=0&&this.keys.indexOf(s.scent)!==this.filter)continue;this.flowGeometry.attributes.position.setXYZ(n,s.p.x,s.p.y,s.p.z);const c=new THREE.Color(SCENTS[s.scent].color);this.flowGeometry.attributes.color.setXYZ(n,c.r,c.g,c.b);n++;}this.flowGeometry.setDrawRange(0,n);this.flowGeometry.attributes.position.needsUpdate=true;this.flowGeometry.attributes.color.needsUpdate=true;this.material.uniforms.uTime.value=this.world.time;this.points.visible=enabled;this.flowPoints.visible=enabled;
 const status={held:b.held,elapsed:b.elapsed,cooldown:b.cooldown,exhale:b.exhale,range:b.range,needsRelease:b.needsRelease};this.world.events.breath?.(status);}
 dispose(){for(const o of [this.points,this.flowPoints]){o.removeFromParent();o.geometry.dispose();o.material.dispose();}}
}
export {visible};
