import * as THREE from './vendor/three.module.js';
import {SCENTS} from './cases.js';
import {assignMaterials,contactAt,describeContact,acousticAt} from './materials.js';
import {Score} from './music.js';
import {SurfaceMarks, ScentScanner, visible} from './perception.js';
const V=THREE.Vector3;
const CENTERS=[[-7,-7],[7,-7],[-7,7],[7,7]];
const COLORS={Eyes:'#c6e2ed',Ears:'#f4ce62',Nose:'#90d9b0',Feel:'#b9a2ef'};
const fract=x=>x-Math.floor(x);
let seed=8307; const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
export class World {
 constructor(canvas,events={}) {
  this.events=events;this.canvas=canvas;this.score=new Score(this);
  this.renderer=events.renderer||new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
  this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.setSize(innerWidth,innerHeight);
  this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.25;
  this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x05080b);this.scene.fog=new THREE.FogExp2(0x071016,.026);
  this.camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.06,110);this.camera.rotation.order='YXZ';
  this.camera.position.set(0,1.68,10);this.yaw=0;this.pitch=0;this.time=0;this.mode='menu';this.active=new Set(['Eyes','Ears']);this.keys={};this.moving=false;
  this.ray=new THREE.Raycaster();this.colliders=[];this.surfaces=[];this.props=[];this.soundSources=[];this.waves=[];this.particleData=[];this.carried=null;this.lastStep=0;this.lastTouch=0;this.lastAmbient=0;this.lastSniff=-20;this.walk=0;this.boots=null;this.footprints=[];this.opened=new Set();this.lastTarget=null;
  this.blackMaterial=new THREE.MeshBasicMaterial({color:0x000000});this.scanner=null;this.earMarks=null;this.touchMarks=null;
  this.materials=new Map();this.geometry={box:new THREE.BoxGeometry(1,1,1),cyl:new THREE.CylinderGeometry(1,1,1,12),sphere:new THREE.SphereGeometry(1,12,8)};
  this.scentKeys=Object.keys(SCENTS);this.scentFilter=-1;this.volume=.6;this.spatial=true;this.sensitivity=1;this.touchMove={x:0,z:0};
  this.group=new THREE.Group();this.scene.add(this.group);this.effects=new THREE.Group();this.scene.add(this.effects);
  this.scene.add(new THREE.HemisphereLight(0xc1dfec,0x263039,2.2));const sun=new THREE.DirectionalLight(0xe5eaff,2);sun.position.set(2,7,4);this.scene.add(sun);
  window.addEventListener('resize',()=>this.resize());this.buildMenu();
 }
 resize(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight)}
 mat(color,emissive=false){const key=color+'-'+emissive;if(this.materials.has(key))return this.materials.get(key);const m=new THREE.MeshStandardMaterial({color,roughness:.8,metalness:.12,emissive:emissive?color:0,emissiveIntensity:emissive?.85:0});this.materials.set(key,m);return m;}
 applyVision(){const eyes=this.active.has('Eyes');for(const mesh of this.surfaces)mesh.material=eyes?mesh.userData.eyeMaterial:this.blackMaterial;this.scene.background.set(eyes?0x05080b:0x000000);this.scene.fog.color.set(eyes?0x071016:0x000000);}

 mesh(kind,x,y,z,sx,sy,sz,color,{solid=false,sample=true,scents=['dust'],parent=this.group,emissive=false}={}){const m=new THREE.Mesh(this.geometry[kind],this.mat(color,emissive));m.position.set(x,y,z);m.scale.set(sx,sy,sz);parent.add(m);m.updateMatrixWorld(true);m.userData.eyeMaterial=m.material;m.userData.scents=scents;this.surfaces.push(m);if(solid)this.colliders.push({x,z,hx:sx/2,hz:sz/2,mesh:m});if(sample&&kind==='box')this.sampleBox(m,scents);return m;}
 box(x,y,z,w,h,d,c,opt={}){return this.mesh('box',x,y,z,w,h,d,c,opt)}
 cyl(x,y,z,r,h,c,opt={}){return this.mesh('cyl',x,y,z,r,h,r,c,opt)}
 sampleBox(m,scents){m.userData.scents=scents;}
 label(text,x,y,z,w=2,color='#c7d8d3',bg='#172528',rotation=0){const canvas=document.createElement('canvas');canvas.width=768;canvas.height=192;const c=canvas.getContext('2d');c.fillStyle=bg;c.fillRect(0,0,768,192);c.fillStyle=color;c.font='bold 52px monospace';c.textAlign='center';c.textBaseline='middle';c.fillText(text,384,96,730);const tex=new THREE.CanvasTexture(canvas);tex.colorSpace=THREE.SRGBColorSpace;const m=this.mat(0xffffff,true).clone();m.map=tex;m.emissiveMap=tex;const plane=new THREE.Mesh(new THREE.PlaneGeometry(w,w/4),m);plane.position.set(x,y,z);plane.rotation.y=rotation;this.group.add(plane);plane.userData.eyeMaterial=m;plane.userData.scents=['dust'];this.surfaces.push(plane);return plane;}
 reset(){this.scanner?.dispose();this.earMarks?.dispose();this.touchMarks?.dispose();this.scanner=null;this.earMarks=null;this.touchMarks=null;this.group.traverse(o=>{const material=o.userData?.eyeMaterial;if(material?.map){material.map.dispose();material.dispose();}});this.group.clear();this.effects.traverse(o=>{o.geometry?.dispose();o.material?.dispose()});this.effects.clear();this.waves=[];this.pendingSounds=[];this.colliders=[];this.surfaces=[];this.props=[];this.soundSources=[];this.particleData=[];this.footprints=[];this.carried=null;this.boots=null;this.opened=new Set();this.points=null;this.billboard=null;this.lastTarget=null;this.lastSniff=-1000;this.lastTouch=-1;}

 buildMenu(){this.reset();this.mode='menu';this.case=null;this.active=new Set(['Eyes','Ears']);this.setSenses(this.active);this.camera.position.set(0,3.9,17);this.camera.lookAt(0,-.2,-7);this.box(0,-.15,0,80,.3,80,0x17232c,{solid:true});
  for(let i=0;i<20;i++){let x=(i%2?1:-1)*(7+Math.floor(i/2)*3.3),z=-8-Math.floor(i/2)*3;let h=7+rnd()*15;this.box(x,h/2,z,5,h,6,i%3===0?0x29323d:0x1b2930);for(let a=0;a<4;a++)for(let b=0;b<6;b++)if(rnd()>.28)this.box(x-1.65+a*1.1,1.6+b*2,z+3.03,.55,.9,.05,rnd()>.5?0xb28e56:0x5b99a1,{emissive:true,sample:false});}
  this.box(0,4,-7,12,5.5,.5,0x152a2f);this.box(0,1,-7,.2,3,.3,0x556365);this.box(-5.9,4,-6.7,.045,5.4,.08,0x7ad4c9,{emissive:true});this.box(5.9,4,-6.7,.045,5.4,.08,0x7ad4c9,{emissive:true});this.billboard=this.label('CASE: NONSENSE',0,4.8,-6.69,11,'#d2ebe3','#152a2f');this.label('INVESTIGATIONS DIVISION',0,3.05,-6.69,6,'#82b8b3','#152a2f');
  for(let x of [-5,5]){this.cyl(x,2.4,2,.06,4.8,0x536c73);this.box(x,4.8,2,.8,.12,.45,0xf3c88e,{emissive:true});const l=new THREE.PointLight(0xe6b276,16,12,2);l.position.set(x,4.5,2);this.group.add(l);}
  for(let i=0;i<20;i++)this.box(0,.016,-20+i*3,.1,.015,1.2,0x829b91,{sample:false});
  this.soundSources.push({pos:new V(-5,2,-5),type:'rain',next:0},{pos:new V(5,2,-8),type:'radio',next:0});this.finishParticles();
 }
 buildCase(c,opened=[]){this.reset();this.case=c;this.mode='game';this.opened=new Set(opened);this.camera.position.set(0,1.68,10.6);this.yaw=0;this.pitch=0;this.camera.rotation.set(0,0,0);this.setSenses(new Set(['Eyes']));
  this.box(0,-.13,0,24,.26,24,0x263336,{solid:false});this.box(0,3.65,0,24,.2,24,0x293c42);this.box(0,3.5,-12,24,.3,.35,0x344147);this.box(0,1.75,-12,24,3.5,.25,0x35494c,{solid:true});this.box(0,1.75,12,24,3.5,.25,0x35494c,{solid:true});this.box(-12,1.75,0,.25,3.5,24,0x35494c,{solid:true});this.box(12,1.75,0,.25,3.5,24,0x35494c,{solid:true});
  for(let sx of [-1,1])for(let sz of [-1,1]){const cx=sx*7,cz=sz*7;this.box(cx,.006,cz,9.8,.02,9.8,0x303a39);this.box(sx*2,1.75,sz*3.35,.2,3.5,2.7,0x526361,{solid:true});this.box(sx*2,1.75,sz*9.65,.2,3.5,4.7,0x526361,{solid:true});this.box(sx*2,3.12,sz*6,.25,.76,2.5,0x526361,{solid:false});this.box(sx*3.35,1.75,sz*2,2.7,3.5,.2,0x526361,{solid:true});this.box(sx*9.65,1.75,sz*2,4.7,3.5,.2,0x526361,{solid:true});this.box(sx*6,3.12,sz*2,2.5,.76,.25,0x526361);
   for(let z of [sz*4.7,sz*7.3])this.box(sx*2,.04,z,.45,.06,.09,0xc8a46a,{sample:false});
  }
  // The cross corridor remains open. Room names are physical signs, never clue markers.
  this.label('EXIT / CASE FILE',0,2.3,11.82,2.6,'#bccec4','#1c3434',Math.PI);
  this.label(c.location,0,2.75,-11.82,3.4,'#bedad3','#193437');
  for(let i=0;i<4;i++)this.decorateRoom(i,c.rooms[i]);
  for(const o of c.objects)this.makeProp(o);
  for(const t of c.trails){for(let i=1;i<t.points.length;i++){const [ax,az]=t.points[i-1],[bx,bz]=t.points[i];const len=Math.hypot(bx-ax,bz-az);for(let n=0;n<len*7;n++){const f=n/(len*7);this.particleData.push({x:ax+(bx-ax)*f+(rnd()-.5)*.3,y:.025+rnd()*.03,z:az+(bz-az)*f+(rnd()-.5)*.3,scent:t.scent,seen:-1000,trail:true});}}}
  this.soundSources.push({pos:new V(0,2,-8),type:'drip',next:0});this.finishParticles();this.scene.updateMatrixWorld(true);
 }
 decorateRoom(i,r){const [x,z]=CENTERS[i];const sgn=z<0?1:-1;const back=z<0?-11.84:11.84;
  this.label(r.name,x,2.8,back,3.7,'#d3d6b6','#263b3d',z<0?0:Math.PI);
  // Ceiling beams, layered skirting, tiled floor and a visible hanging light.
  this.box(x,3.45,z,10,.14,.15,0x78807b);this.box(x,3.2,z,.12,.5,.12,0x344047);this.box(x,2.93,z,1.35,.13,.45,r.type==='studio'?0x91a6de:0xe1bc7a,{emissive:true,sample:false});
  const light=new THREE.PointLight(r.type==='studio'?0x889ded:r.type==='greenhouse'?0x83c5a6:0xf2cb9a,26,14,2);light.position.set(x,2.75,z);this.group.add(light);
  for(let j=-4;j<=4;j++){this.box(x+j,.025,z,.016,.012,9.6,0x485354,{sample:false});this.box(x,.025,z+j,9.6,.012,.016,0x485354,{sample:false});}
  this.box(x,1.2,back-(z<0?-.06:.06),9.7,.06,.1,r.color,{sample:false});
  if(['studio','archive'].includes(r.type))for(let j=-3;j<=3;j++)this.box(x+j,1.7,back+(z<0?.05:-.05),.6,1.5,.14,r.color,{sample:false});
  if(r.type==='greenhouse'){for(let j=-4;j<=4;j+=2){this.box(x+j,2.5,back+.1,.045,1.7,.07,0x718d85);this.box(x+j,2.5,back+.07,1.8,1.6,.03,0x203e49);}}
  if(r.type==='kitchen'||r.type==='utility'){for(let j=0;j<3;j++){this.cyl(x-4.3+j*.22,2.5,z,.045,1.6,0x8f9c98);}}
  // Room ambience props placed off the investigation path.
  this.cyl(x+4.2,.35,z+4.1,.3,.7,0x304c47);for(let j=0;j<4;j++){const leaf=this.box(x+4.2+(rnd()-.5)*.5,.85+rnd()*.3,z+4.1+(rnd()-.5)*.5,.12,.8,.12,0x4e7957);leaf.rotation.z=(rnd()-.5);}
 }
 makeProp(o){const [cx,cz]=CENTERS[o.room],x=cx+o.x,z=cz+o.z;const g=new THREE.Group();this.group.add(g);const list=[];const opt={parent:g,scents:o.scents||['dust']};const box=(dx,y,dz,w,h,d,c,solid=false)=>{const m=this.box(x+dx,y,z+dz,w,h,d,c,{...opt,solid});list.push(m);return m};const cyl=(dx,y,dz,r,h,c)=>{const m=this.cyl(x+dx,y,z+dz,r,h,c,opt);list.push(m);return m};
  const table=()=>{box(0,.88,0,1.8,.12,1.1,0x65513d,true);for(let a of [-.73,.73])for(let b of [-.4,.4])box(a,.43,b,.09,.86,.09,0x303a3b);};
  let aimY=1;
  switch(o.kind){
   case 'paper':case 'book':table();box(0,.968,0,o.kind==='book'?.55:.65,.04,.45,o.kind==='book'?0x75503e:0xc8c4a8);for(let i=0;i<5;i++)box(-.02,.992,-.14+i*.06,.44,.005,.012,0x525e57);break;
   case 'desk':table();box(0,.66,0,1.4,.28,.8,0x534536);box(0,.67,.42,.38,.035,.03,0xbba87c);box(.38,1.1,-.1,.35,.4,.25,0x394f4f);box(-.35,.97,0,.55,.025,.4,0xc5c5b2);break;
   case 'cup':table();cyl(0,1.08,0,.14,.25,0xb7c7bf);cyl(0,1.211,0,.115,.005,0x362721);box(0,.96,0,.42,.025,.4,0xe2d6b2);break;
   case 'rack':box(0,.08,0,1.1,.12,.6,0x373e43,true);box(0,1.05,0,.09,2,.09,0x657478);box(0,1.94,0,1.3,.08,.08,0x657478);box(0,1.24,.04,.72,1.15,.23,0x384c6e);box(-.48,1.48,0,.2,.64,.23,0x384c6e);box(.48,1.48,0,.2,.64,.23,0x384c6e);box(.02,1.63,.17,.13,.12,.015,0xbeaf93);aimY=1.45;break;
   case 'radio':table();box(0,1.23,0,.8,.5,.35,0x374448);for(let j=-3;j<=3;j++)box(j*.065-.1,1.24,.185,.026,.35,.02,0x101c22);cyl(.24,1.1,.2,.055,.06,0xcac5a4);box(.18,1.34,.187,.2,.07,.012,0x92baab);break;
   case 'vent':box(0,1.32,0,1.15,1.6,.32,0x34444b,true);for(let j=0;j<9;j++)box(0,.7+j*.14,.18,.94,.05,.04,0x748984);box(0,.48,.18,.38,.08,.025,0xb9ac82);aimY=1.4;break;
   case 'oven':box(0,.75,0,1.7,1.5,1,0x607574,true);box(0,.8,.52,1.2,.7,.025,0x17242c);box(0,1.24,.55,1.15,.06,.05,0xa4b3a3);box(0,.3,.57,1.3,.05,.05,0xabb7ab);for(let j=-1;j<=1;j++)cyl(j*.45,1.53,0,.16,.02,0x263234);break;
   case 'cloth':table();box(0,.98,0,.75,.09,.54,o.id.includes('apron')?0x526a8a:0x9caa98);for(let j=0;j<4;j++)box(-.24+j*.14,1.035,0,.035,.013,.54,0x657d86);break;
   case 'cabinet':box(0,.9,0,1.6,1.8,.85,0x655945,true);for(let y of [.15,.72,1.3,1.78])box(0,y,.1,1.6,.07,1,0x8a785d);box(-.78,.9,.4,.08,1.8,.08,0x8a785d);box(.78,.9,.4,.08,1.8,.08,0x8a785d);box(0,.9,.46,1.4,1.65,.02,0x3c443d);aimY=.8;break;
   case 'sack':box(0,.44,0,.85,.88,.66,0xa1936b,true);box(0,.91,0,.5,.08,.54,0xc1b18b);box(0,.58,.34,.34,.25,.02,0xd9c9a2);aimY=.6;break;
   case 'trolley':box(0,.5,0,1.3,.1,.75,0x526260,true);for(let a of [-.5,.5])for(let b of [-.26,.26])cyl(a,.16,b,.11,.15,0x172528);box(.56,.83,0,.055,.8,.055,0xa2afa5);box(-.56,.83,0,.055,.8,.055,0xa2afa5);box(0,1.2,0,1.2,.05,.07,0xa2afa5);cyl(0,.79,0,.29,.52,0x857440);break;
   case 'board':box(0,1.35,0,1.45,1.35,.1,0x725e44,true);for(let a=0;a<3;a++)for(let b=0;b<2;b++)box(-.43+a*.43,1.65-b*.6,.07,.32,.44,.02,0xc3c8b0);aimY=1.4;break;
   case 'chair':box(0,.58,0,.8,.1,.8,0x6d5651,true);box(0,1.03,-.38,.8,.85,.08,0x6d5651);for(let a of [-.3,.3])for(let b of [-.3,.3])box(a,.27,b,.06,.54,.06,0x869188);break;
   case 'window':box(0,1.45,0,1.8,2.3,.1,0x657b78,true);box(0,1.55,.07,1.5,1.8,.03,0x173841);box(0,1.6,.1,.05,1.8,.04,0x8b9e90);box(0,1.6,.1,1.5,.05,.04,0x8b9e90);for(let i=0;i<12;i++){const m=box((rnd()-.5)*1.5,.04,.1+rnd()*.8,.12,.025,.13,0x7aafa4);m.rotation.y=rnd()*5;}aimY=1.4;break;
   case 'plant':table();for(let a of [-.5,0,.5]){cyl(a,1.05,0,.17,.22,0x987453);box(a,1.42,0,.035,.65,.035,0x607a4e);for(let j=0;j<3;j++){const m=box(a+(rnd()-.5)*.2,1.6+j*.1,0,.17,.08,.15,0xb99bb7);m.rotation.z=j;}}aimY=1.4;break;
   case 'bottles':table();for(let a of [-.4,0,.4]){cyl(a,1.17,0,.1,.38,0x508875);cyl(a,1.42,0,.045,.13,0x657968);box(a,1.17,.104,.12,.16,.02,0xb8c6a6);}break;
   case 'sink':box(0,.9,0,1.5,.15,.9,0x9ba9a1,true);box(0,.91,0,1.15,.12,.6,0x465b5b);cyl(.45,1.13,-.25,.04,.4,0xaab9b4);box(.35,1.3,-.25,.25,.05,.05,0xaab9b4);for(let a of [-.6,.6])box(a,.44,0,.06,.88,.06,0x829b91);break;
   case 'generator':box(0,.62,0,1.5,1.2,.9,0x596857,true);box(0,.65,.46,1.2,.8,.03,0x243c3b);for(let i=-3;i<=3;i++)box(i*.14,.65,.48,.025,.65,.02,0x7f9080);box(0,1.25,0,1.2,.08,.65,0xa19157);break;
   case 'mic':table();box(0,1.22,0,.045,.5,.045,0x919d9a);cyl(0,1.55,0,.12,.34,0xb0beb1);for(let i=0;i<4;i++)box(0,1.42+i*.07,.12,.18,.025,.025,0x3d5555);box(.55,1.04,0,.24,.14,.2,0x814b43);aimY=1.5;break;
   case 'console':box(0,.7,0,1.9,1.4,1,0x405155,true);box(0,1.44,0,1.95,.1,1.05,0x73817a);for(let i=0;i<8;i++){box(-.72+i*.2,1.5,0,.04,.04,.5,0x213539);box(-.72+i*.2,1.53,-.2+rnd()*.4,.1,.04,.08,0xc6c6a2);}for(let i=0;i<3;i++)box(-.6+i*.6,1.7,-.3,.4,.3,.08,0x88b9a2);aimY=1.3;break;
   case 'pedestal':box(0,.65,0,.85,1.3,.75,0x675746,true);box(0,1.33,0,1.05,.07,.9,0x9a896a);box(.25,1.53,-.18,.25,.35,.04,0xc2bc98);break;
   case 'award':box(0,.65,.1,.55,.18,.42,0xa9a08a);box(0,.86,.1,.32,.32,.28,0xb49c57);box(0,1.1,.1,.48,.18,.18,0xbda761);aimY=.85;break;
   default:table();
  }
  // For hidden objects, lift the observation target away from its containing furniture after opening.
  if(o.hiddenBy){g.position.z+=.75;g.visible=this.opened.has(o.hiddenBy);for(const m of list)m.updateMatrixWorld(true);}
  for(const m of list)m.userData.propId=o.id;assignMaterials(list,o,this.case?.id);
  const p={...o,group:g,meshes:list,pos:new V(x,aimY,z+(o.hiddenBy?.75:0)),worldX:x,worldZ:z,opened:this.opened.has(o.id)};this.props.push(p);
  if(o.sound)this.soundSources.push({pos:new V(x,1,z),type:o.sound,propId:o.id,next:rnd()*3});
 }
 finishParticles(){this.scene.updateMatrixWorld(true);this.scanner=new ScentScanner(this);this.earMarks=new SurfaceMarks(this.scene,0xffcf64,5,2048);this.touchMarks=new SurfaceMarks(this.scene,0xbea1ff,180,6144);this.applyVision();}
 setSenses(s){this.active=new Set(s);if(!s.has('Ears')&&this.score.gain){this.score.level=0;this.score.gain.gain.cancelScheduledValues(this.audio.currentTime);this.score.gain.gain.setValueAtTime(0,this.audio.currentTime);}this.applyVision();if(!s.has('Nose'))this.endSniff();if(!s.has('Ears')&&this.master)this.master.gain.setTargetAtTime(0,this.audio.currentTime,.04);else if(this.master)this.master.gain.setTargetAtTime(this.volume,this.audio.currentTime,.04);if(s.has('Feel')&&this.mode==='game'){this.touch(true);this.footTouch();}}

 initAudio(){if(!this.audio){const A=window.AudioContext||window.webkitAudioContext;if(!A)return;this.audio=new A();this.master=this.audio.createGain();this.master.gain.value=this.active.has('Ears')?this.volume:0;this.master.connect(this.audio.destination);}this.audio.resume();this.score.unlock();}
 playSound(pos,type,strength=1,material=null){if(!this.audio||!this.active.has('Ears'))return;const ac=this.audio,now=ac.currentTime,dist=this.camera.position.distanceTo(pos),gain=ac.createGain();gain.gain.setValueAtTime(Math.min(.32,strength*.7/(1+dist*.22)),now);const duration=material?.duration??(['fan','airflow','tape'].includes(type)?1.1:type==='voice'?.75:type==='hollow'?.65:type==='tape'?.5:type==='radio'?.35:.15);gain.gain.exponentialRampToValueAtTime(.001,now+duration);let out=gain;if(this.spatial){const pan=ac.createStereoPanner();const rel=pos.clone().sub(this.camera.position);const right=new V(1,0,0).applyQuaternion(this.camera.quaternion);pan.pan.value=THREE.MathUtils.clamp(rel.normalize().dot(right),-1,1);gain.connect(pan);pan.connect(this.master);out=pan;}else gain.connect(this.master);
  const osc=ac.createOscillator();osc.type=['step','knock','stomp','hollow'].includes(type)?'triangle':type==='voice'?'sawtooth':'sine';const freqs={step:110,knock:230,hollow:95,stomp:75,radio:330,hum:90,fan:130,drip:940,tick:1250,tape:175,voice:140,rain:580,airflow:130};osc.frequency.setValueAtTime(material?.frequency||freqs[type]||150,now);if(type==='voice')osc.frequency.linearRampToValueAtTime(100+Math.sin(this.time)*40,now+duration);const filter=ac.createBiquadFilter();filter.type='lowpass';filter.frequency.value=material?250+(1-material.absorb)*6500:5000;osc.connect(filter);filter.connect(gain);if(['airflow','fan','tape','rain'].includes(type)){const buffer=ac.createBuffer(1,Math.ceil(ac.sampleRate*duration),ac.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(rnd()*2-1)*(type==='fan'?.025:type==='tape'?.06:.45);const noise=ac.createBufferSource();noise.buffer=buffer;noise.connect(filter);noise.start(now);noise.stop(now+duration);noise.onended=()=>noise.disconnect();}osc.start(now);osc.stop(now+duration);osc.onended=()=>{osc.disconnect();filter.disconnect();gain.disconnect();if(out!==gain)out.disconnect()};
 }
 emitSound(pos,type='knock',power=1,material=null){this.playSound(pos,type,power,material);const profiles={step:[10,5,8],stomp:[22,5,16],knock:[14,4,12],hollow:[17,5,15],tick:[6,2,7],voice:[14,4,16],drip:[8,3,10],fan:[10,3,12],hum:[8,3,10],tape:[9,2,9],radio:[12,3,14],rain:[12,2,15],airflow:[18,4,13]};const profile=profiles[type]||profiles.knock;const count=Math.round(profile[0]*power);for(let i=0;i<count;i++){const a=(i/count)*Math.PI*2+rnd()*.25;const dir=new V(Math.cos(a), (rnd()-.45)*.7,Math.sin(a)).normalize();let origin=pos.clone(),travel=0;const points=[origin.clone()],hits=[];for(let b=0;b<profile[1];b++){this.ray.set(origin,dir);this.ray.far=profile[2];const hit=this.ray.intersectObjects(this.surfaces,false).find(h=>h.distance>.045&&h.object.visible&&h.object.parent.visible);if(!hit){points.push(origin.clone().addScaledVector(dir,8));break}travel+=hit.distance;points.push(hit.point.clone());hits.push({p:hit.point.clone(),hit,at:this.time+travel/15,done:false});const normal=hit.face.normal.clone().transformDirection(hit.object.matrixWorld);dir.reflect(normal);origin=hit.point.clone().addScaledVector(dir,.05);}
   if(points.length>1){const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(new Float32Array(900),3));const mat=new THREE.LineBasicMaterial({color:0xffca58,transparent:true,opacity:0,depthTest:false,depthWrite:false});const line=new THREE.LineSegments(geo,mat);line.renderOrder=5;this.effects.add(line);this.waves.push({line,points,hits,start:this.time,life:Math.min(7,travel/15+.5),type,material});}}
 }
 touch(force=false){if(!this.active.has('Feel'))return null;if(this.time-this.lastTouch<.035&&!force)return null;this.lastTouch=this.time;this.camera.updateMatrixWorld(true);const dir=new V();this.camera.getWorldDirection(dir);this.ray.set(this.camera.position,dir);this.ray.far=2.0;const hit=this.ray.intersectObjects(this.surfaces,false).find(h=>visible(h.object));if(hit)this.addTouch(hit);else{this.contact=null;this.events.tactile?.(null);}return hit;}
 footTouch(){if(!this.active.has('Feel'))return;const origin=this.camera.position.clone();origin.x+=Math.sin(this.walk*8)>.0?.1:-.1;this.ray.set(origin,new V(0,-1,0));this.ray.far=2;const hit=this.ray.intersectObjects(this.surfaces,false).find(h=>visible(h.object));if(hit)this.touchMarks?.add(hit,this.time,.29);}
 addTouch(hit){if(hit?.object&&this.active.has('Feel')){this.touchMarks?.add(hit,this.time,.38);this.contact=contactAt(hit);this.events.tactile?.(this.contact);}}
 beginSniff(){if(!this.active.has('Nose')||!this.scanner)return false;const ok=this.scanner.begin();if(!ok&&this.scanner.breath.cooldown>0)this.events.message?.('Catch your breath: '+Math.ceil(this.scanner.breath.cooldown)+' seconds.');return ok;}
 endSniff(){this.scanner?.release();}
 filterScent(id){this.scentFilter=id?this.scentKeys.indexOf(id):-1;this.scanner?.setFilter(id);}
 target(){if(this.mode!=='game')return null;const dir=new V();this.camera.getWorldDirection(dir);this.ray.set(this.camera.position,dir);this.ray.far=3.1;const hit=this.ray.intersectObjects(this.surfaces,false).find(h=>visible(h.object));if(!hit?.object.userData.propId)return null;const p=this.props.find(p=>p.id===hit.object.userData.propId);if(!p||p.hiddenBy&&!this.opened.has(p.hiddenBy))return null;const sense=[...this.active][0];if(sense==='Feel'&&hit.distance>2.0)return null;if(sense==='Nose'&&!this.scanner?.hasNear(hit,this.time))return null;if(sense==='Ears'&&!this.earMarks?.hasNear(hit,this.time))return null;return {prop:p,distance:hit.distance,point:hit.point,sense,hit};}

 openSecret(id){this.opened.add(id);const p=this.props.find(p=>p.id===id);if(p)p.opened=true;this.props.filter(p=>p.hiddenBy===id).forEach(p=>{p.group.visible=true});this.scene.updateMatrixWorld(true);this.scanner?.rebuild();this.events.opened?.([...this.opened]);}
 interact(){const target=this.target();if(target){if(target.sense==='Ears')this.knock();if(target.sense==='Feel')this.addTouch(target.hit);this.events.inspect?.(target.prop,target.sense);}else if(this.active.has('Ears'))this.knock();else if(this.active.has('Feel')){this.touch(true);this.events.message?.('You trace the surface within reach.');}else this.events.message?.('Move closer and look directly at an object.');}
 knock(){if(!this.active.has('Ears'))return;this.camera.updateMatrixWorld(true);const d=new V();this.camera.getWorldDirection(d);this.ray.set(this.camera.position,d);this.ray.far=2.2;const hit=this.ray.intersectObjects(this.surfaces,false).find(h=>visible(h.object));if(!hit){this.events.message?.('Move within two meters to knock on a surface.');return;}const profile=acousticAt(hit),normal=hit.face.normal.clone().transformDirection(hit.object.matrixWorld);this.earMarks?.add(hit,this.time,.55);this.score.duck(2);this.emitSound(hit.point.clone().addScaledVector(normal,.06),'knock',1.1,profile);this.events.message?.(profile.label+'. Compare another part of the surface.');}
 action(){if(this.active.has('Nose'))this.beginSniff();else if(this.active.has('Ears')){this.emitSound(new V(this.camera.position.x,.2,this.camera.position.z),'stomp',1.2);this.events.message?.('You stamp your foot.');}else if(this.active.has('Feel'))this.touch(true);else this.events.message?.('Eyes observes ordinary visible detail. Use E to inspect.');}
 look(dx,dy){this.yaw-=dx*.0022*this.sensitivity;this.pitch=THREE.MathUtils.clamp(this.pitch-dy*.0022*this.sensitivity,-1.35,1.35);this.camera.rotation.set(this.pitch,this.yaw,0)}
 blocked(x,z){if(Math.abs(x)>11.65||Math.abs(z)>11.65)return true;return this.colliders.some(c=>Math.abs(x-c.x)<c.hx+.24&&Math.abs(z-c.z)<c.hz+.24)}
 roomName(){const x=this.camera.position.x,z=this.camera.position.z;if(Math.abs(x)<2.2||Math.abs(z)<2.2)return 'CENTRAL HALL';const i=z<0?(x<0?0:1):(x<0?2:3);return this.case?.rooms[i].name||''}
 throwObject(){if(this.mode!=='game')return;if(this.carried){const held=this.carried,p=held.prop;this.carried=null;const d=new V();this.camera.getWorldDirection(d);const dest=this.camera.position.clone().addScaledVector(d,2.1);dest.y=.94;this.ray.set(this.camera.position,d);this.ray.far=2.2;const hit=this.ray.intersectObjects(this.surfaces,false).find(h=>!held.meshes.includes(h.object)&&h.object.parent.visible);if(hit)dest.copy(hit.point).addScaledVector(d,-.35);const delta=dest.clone().sub(p.pos);for(const m of held.meshes){m.visible=true;m.position.add(delta);}p.pos.copy(dest);this.scene.updateMatrixWorld(true);this.scanner?.rebuild();this.emitSound(dest,'knock',1.5);this.events.message?.('Object tossed. Its impact carries through the room.');}else{const t=this.target();if(!t||!['cup','cloth','book','paper','bottles'].includes(t.prop.kind)){this.events.message?.('Look at a small object within reach to pick it up.');return}const meshes=t.prop.meshes.slice(5);this.carried={prop:t.prop,meshes};meshes.forEach(m=>m.visible=false);this.events.message?.('Object held. Press G again to toss it.');}}

 tick(dt,playing){this.time+=dt;this.score.update(dt);this.scanner?.update(dt,this.active.has('Nose'),playing||this.mode==='menu');this.earMarks?.update(this.time,this.active.has('Ears'));this.touchMarks?.update(this.time,this.active.has('Feel'));
  if(this.mode==='menu'){this.camera.position.x=this.reducedMotion?0:Math.sin(this.time*.055)*.7;this.camera.lookAt(0,-.2,-7);if(this.billboard){const titleMaterial=this.billboard.userData.eyeMaterial;const c=titleMaterial.map.image.getContext('2d');const glitch=Math.sin(this.time*1.71)>.993&&Math.sin(this.time*.73)>.1;c.fillStyle='#152a2f';c.fillRect(0,0,768,192);c.fillStyle=glitch?'#82b5b0':'#d2ebe3';c.font='bold 52px monospace';c.textAlign='center';c.textBaseline='middle';c.fillText(glitch?'CASE: NO SENSE':'CASE: NONSENSE',384,96,730);titleMaterial.map.needsUpdate=true;}}
  else if(playing){let mx=(this.keys.KeyD?1:0)-(this.keys.KeyA?1:0)+this.touchMove.x,mz=(this.keys.KeyW?1:0)-(this.keys.KeyS?1:0)+this.touchMove.z;const len=Math.hypot(mx,mz);this.moving=len>.03;if(len>1){mx/=len;mz/=len}const speed=(this.keys.ShiftLeft?3.7:2.55)*dt;const dx=(Math.cos(this.yaw)*mx-Math.sin(this.yaw)*mz)*speed,dz=(-Math.sin(this.yaw)*mx-Math.cos(this.yaw)*mz)*speed;const p=this.camera.position;if(!this.blocked(p.x+dx,p.z))p.x+=dx;if(!this.blocked(p.x,p.z+dz))p.z+=dz;
   if(this.moving){this.walk+=Math.hypot(dx,dz);p.y=1.68+(this.reducedMotion?0:Math.sin(this.walk*8)*.017);if(this.time-this.lastStep>.48){this.lastStep=this.time;this.emitSound(new V(p.x,.12,p.z),'step',.55);if(this.active.has('Feel'))this.footTouch();this.transferScent();}}if(this.active.has('Feel'))this.touch();
   if(this.keys.ArrowLeft)this.look(-60*dt,0);if(this.keys.ArrowRight)this.look(60*dt,0);if(this.keys.ArrowUp)this.look(0,-60*dt);if(this.keys.ArrowDown)this.look(0,60*dt);
   const t=this.target();this.lastTarget=t;this.events.target?.(t);this.events.room?.(this.roomName());
  }
  if(this.active.has('Ears'))for(const source of this.soundSources){if(this.time>source.next){source.next=this.time+(source.type==='tick'?3.5:source.type==='voice'?8:source.type==='tape'?4:4+rnd()*2);this.emitSound(source.pos,source.type,source.type==='voice'?.85:.65);if(source.type==='voice'){this.pendingSounds??=[];this.pendingSounds.push({at:this.time+.95,pos:source.pos.clone(),type:'tick'},{at:this.time+1.19,pos:source.pos.clone(),type:'tick'});}}}
  if(this.pendingSounds)for(let i=this.pendingSounds.length-1;i>=0;i--){const event=this.pendingSounds[i];if(this.time>=event.at){if(this.active.has('Ears'))this.emitSound(event.pos,event.type,.55);this.pendingSounds.splice(i,1);}}
  for(let i=this.waves.length-1;i>=0;i--){const w=this.waves[i],age=this.time-w.start;if(age>w.life){this.effects.remove(w.line);w.line.geometry.dispose();w.line.material.dispose();this.waves.splice(i,1);continue}w.line.visible=this.active.has('Ears');w.line.material.opacity=Math.max(0,.45*(1-age/w.life));const front=age*15,back=Math.max(0,front-3.2);let distance=0,drawn=0;const buf=w.line.geometry.attributes.position;for(let j=1;j<w.points.length;j++){const a=w.points[j-1],b=w.points[j],length=a.distanceTo(b);if(front>=distance&&back<=distance+length){const lo=Math.max(0,(back-distance)/length),hi=Math.min(1,(front-distance)/length);const response=j===1?w.material:(w.hits[j-2]?acousticAt(w.hits[j-2].hit):null),ripple=response?.ripple||.015,steps=8;const offset=new V().subVectors(b,a).cross(new V(0,1,0)).normalize();const point=t=>a.clone().lerp(b,t).addScaledVector(offset,Math.sin(t*length*24-age*20)*ripple);for(let k=0;k<steps;k++){const pa=point(lo+(hi-lo)*k/steps),pb=point(lo+(hi-lo)*(k+1)/steps);buf.setXYZ(drawn++,pa.x,pa.y,pa.z);buf.setXYZ(drawn++,pb.x,pb.y,pb.z);}}distance+=length;}w.line.geometry.setDrawRange(0,drawn);buf.needsUpdate=true;w.line.geometry.computeBoundingSphere();for(const h of w.hits)if(!h.done&&this.time>=h.at){h.done=true;this.earMarks?.add(h.hit,this.time,.82);}}
  this.renderer.render(this.scene,this.camera);
 }
 transferScent(){const p=this.camera.position;for(const t of this.case.trails){for(let i=1;i<t.points.length;i++){const a=new THREE.Vector2(...t.points[i-1]),b=new THREE.Vector2(...t.points[i]),q=new THREE.Vector2(p.x,p.z),v=b.clone().sub(a);const f=THREE.MathUtils.clamp(q.clone().sub(a).dot(v)/v.lengthSq(),0,1);if(q.distanceTo(a.addScaledVector(v,f))<.28)this.boots={scent:t.scent,left:12};}}
  if(this.boots&&this.boots.left-->0){const s=this.boots.scent;this.footprints.push({x:p.x,z:p.z,scent:s});if(this.footprints.length>40)this.footprints.shift(); // A limited pool of actual transferred traces.
   for(let n=0;n<6;n++){this.particleData.push({x:p.x+(rnd()-.5)*.2,y:.035,z:p.z+(rnd()-.5)*.24,scent:s,transfer:true});}const transfers=this.particleData.filter(p=>p.transfer);if(transfers.length>240)this.particleData.splice(this.particleData.findIndex(p=>p.transfer),6);}

 }
}
export {THREE,CENTERS,COLORS};
